"""
train_bid_regressor.py
=======================

Step 4 of the roadmap: train the bid regressor on the
(hand, trump) -> tricks dataset generated by
generate_bid_dataset.py.

Trains and compares three model families (matching the docstring
in feature_extractor.py: "Used by: Linear Regression, Random
Forest, XGBoost"):

    1. Linear Regression      - fast, interpretable baseline
    2. Random Forest Regressor
    3. XGBoost Regressor

Picks the best model by held-out test MAE (mean absolute error in
tricks, which maps directly to "how far off is the predicted bid"),
saves it, and also emits a BidModel wrapper (bid_model.py) that
implements the .predict(game, player) interface environment.py's
mode="full" expects.

Usage
-----
    python3 train_bid_regressor.py --data bid_dataset.csv
"""

import argparse
import json

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor


NON_FEATURE_COLS = ["hand", "trump", "tricks"]


def load_dataset(path):
    df = pd.read_csv(path)

    feature_cols = [
        c for c in df.columns if c not in NON_FEATURE_COLS
    ]

    X = df[feature_cols].values.astype(np.float32)
    y = df["tricks"].values.astype(np.float32)

    return df, X, y, feature_cols


def evaluate(name, model, X_test, y_test):
    preds = model.predict(X_test)

    mae = mean_absolute_error(y_test, preds)
    rmse = np.sqrt(mean_squared_error(y_test, preds))
    r2 = r2_score(y_test, preds)

    # Bid-relevant metric: after rounding + clipping to the legal
    # bid range, how often is the prediction exactly right / within 1?
    rounded = np.clip(np.round(preds), 2, 13)
    exact = np.mean(rounded == y_test)
    within_1 = np.mean(np.abs(rounded - y_test) <= 1)

    print(
        f"{name:16s} | MAE={mae:.4f}  RMSE={rmse:.4f}  R2={r2:.4f}  "
        f"exact_bid={exact:.3f}  within_1={within_1:.3f}"
    )

    return {
        "mae": float(mae),
        "rmse": float(rmse),
        "r2": float(r2),
        "exact_bid_rate": float(exact),
        "within_1_rate": float(within_1),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", type=str, default="bid_dataset.csv")
    parser.add_argument("--test_size", type=float, default=0.2)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--out_prefix", type=str, default="bid_model")
    args = parser.parse_args()

    df, X, y, feature_cols = load_dataset(args.data)

    print(f"Loaded {len(df)} rows, {len(feature_cols)} features")
    print(f"Target (tricks) stats: mean={y.mean():.3f} std={y.std():.3f} "
          f"min={y.min():.0f} max={y.max():.0f}\n")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=args.test_size, random_state=args.seed
    )

    results = {}
    models = {}

    # ---------------------------------------------------------
    # 1. Linear Regression
    # ---------------------------------------------------------
    lin = LinearRegression()
    lin.fit(X_train, y_train)
    results["linear_regression"] = evaluate(
        "LinearRegression", lin, X_test, y_test
    )
    models["linear_regression"] = lin

    # ---------------------------------------------------------
    # 2. Random Forest
    # ---------------------------------------------------------
    rf = RandomForestRegressor(
        n_estimators=300,
        max_depth=12,
        min_samples_leaf=5,
        n_jobs=-1,
        random_state=args.seed,
    )
    rf.fit(X_train, y_train)
    results["random_forest"] = evaluate(
        "RandomForest", rf, X_test, y_test
    )
    models["random_forest"] = rf

    # ---------------------------------------------------------
    # 3. XGBoost
    # ---------------------------------------------------------
    xgb = XGBRegressor(
        n_estimators=400,
        max_depth=5,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        reg_lambda=1.0,
        random_state=args.seed,
        n_jobs=-1,
    )
    xgb.fit(X_train, y_train)
    results["xgboost"] = evaluate(
        "XGBoost", xgb, X_test, y_test
    )
    models["xgboost"] = xgb

    # ---------------------------------------------------------
    # Pick best by MAE
    # ---------------------------------------------------------
    best_name = min(results, key=lambda k: results[k]["mae"])
    best_model = models[best_name]

    print(f"\nBest model: {best_name} "
          f"(MAE={results[best_name]['mae']:.4f})")

    # Feature importance for the tree models, coefficients for linear
    if best_name == "linear_regression":
        importances = dict(zip(feature_cols, best_model.coef_.tolist()))
    else:
        importances = dict(
            zip(feature_cols, best_model.feature_importances_.tolist())
        )

    top_features = sorted(
        importances.items(), key=lambda kv: abs(kv[1]), reverse=True
    )[:10]

    print("\nTop 10 features:")
    for name, val in top_features:
        print(f"  {name:20s} {val:+.4f}")

    # ---------------------------------------------------------
    # Save everything
    # ---------------------------------------------------------
    joblib.dump(best_model, f"{args.out_prefix}.joblib")

    metadata = {
        "best_model": best_name,
        "feature_cols": feature_cols,
        "results": results,
        "min_bid": 2,
        "max_bid": 13,
    }

    with open(f"{args.out_prefix}_metadata.json", "w") as f:
        json.dump(metadata, f, indent=2)

    print(f"\nSaved model -> {args.out_prefix}.joblib")
    print(f"Saved metadata -> {args.out_prefix}_metadata.json")


if __name__ == "__main__":
    main()
